CREATE TABLE ESTOQUE(
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	DESCRICAO VARCHAR2(45) NOT NULL,
	VALOR NUMERIC(10,2) NOT NULL DEFAULT '0',
	PAGO VARCHAR(3) NOT NULL DEFAULT'NAO',
	DATA DATE NULL,
	PRIMARY KEY (ID)
);

INSERT INTO PEDIDOS(DESCRICAO,VALOR,DATA) VALUES ('TV',2200,2016-01-10);
INSERT INTO PEDIDOS(DESCRICAO,VALOR,DATA) VALUES ('TV',2200,2016-01-13);
INSERT INTO PEDIDOS(DESCRICAO,VALOR,DATA) VALUES ('TV',2200,2016-01-14);
INSERT INTO PEDIDOS(DESCRICAO,VALOR,DATA) VALUES ('TV',2200,2016-01-15);

SELECT*FROM SOFTBLUE.PEDIDOS;
SELECT*FROM PEDIDOS WHERE PAGO= 'NÃO' AND TO_DAYS(NOW()) - TO_DAYS >3;

CREATE TABLE ESTOQUE(
ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
DESCRICAO VARCHAR(45) NOT NULL,
PRIMARY KEY(ID)
);

INSERT INTO ESTOQUE (DESCRICAO,QUANTIDADE) VALUES ('TV','5');
DELIMITER $$

-- CRIANDO UMA PRODUCERE
CREATE PROCEDURE Nome

-- INVOCANDO UMA STORED PROCEDURE
CALL Nome
EXECUTE Nome

-- EXCLUINDO UMA STORED PROCEDURE
DROP PROCEDURE Nome

-- CRIANDO UM TRIGGER
CREATE TRIGGER T_LIMPA_PEDIDO BEFORE INSERT ON ESTOQUE FOR EACH ROW 
BEGIN
CALL LIMPA_PEDIDO();
END$$

-- BEFORE INSERT
-- BEFORE UPDATE
-- BEFORE DELETE
-- AFTER INSERT
-- AFTER UDATE
-- AFTER DELETE
-- TEMPORAIS

-- Excluir trigger
DROP TRIGGER Nome